FROM mysql:8.0

# Đặt các biến môi trường
ENV MYSQL_DATABASE=summarease
ENV MYSQL_ALLOW_EMPTY_PASSWORD=yes

# Cổng MySQL
EXPOSE 3306

# Đặt kiểm tra sức khỏe
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
  CMD mysqladmin ping -h localhost -u root || exit 1