FROM php:8.2-apache

RUN apt-get update && apt-get install -y libzip-dev unzip git && \
    docker-php-ext-install pdo_mysql zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html
COPY ./backend-php /var/www/html

RUN chown -R www-data:www-data /var/www/html
EXPOSE 80
